apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mjpg-streamer
  name: deployment-mjpg-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjpg-streamer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mjpg-streamer
    spec:
      containers:
      - image: fufuhu/mjpg-streamer
        name: mjpg-streamer
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /mnt
          name: volume-device
      - image: fufuhu/django-mjpg
        name: django-mjpg
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        envFrom:
        - configMapRef:
            name: configmap-mjpg-streamer
      - image: fufuhu/s3-uploder
        name: s3-uploader
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        envFrom:
        - configMapRef:
            name: configmap-mjpg-streamer
        - secretRef:
            name: secret-mjpg-streamer
      volumes:
      - name: volume-device
        hostPath:
          path: /dev
      - name: volume-tmp
        emptyDir: {}