apiVersion: v1
kind: Service
metadata:
  labels:
    app: mjpg-streamer
  name: service-mjpg-streamer
spec:
  ports:
  - name: mjpg-steamer-port
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: mjpg-streamer
  type: NodePort